// =====================================================
// 审计事件类型枚举 — Phase 1 Task 2.1 (CODE-EXECUTION-PLAN §3.1 audit)
// 架构映射: L2 审计要求(4 类事件: 用户/数据/系统/安全)
//
// 约定:
//   - action 前缀 = 事件类别(写入 audit_logs.action)
//     SECURITY:xxx  = 安全事件
//     SYSTEM:xxx    = 系统事件
//     AUTH:xxx      = 用户认证事件
//     CONFIG:xxx    = 配置变更事件
//   - 业务数据事件(INSERT:xxx / UPDATE:xxx / DELETE:xxx)由 DB trigger 自动产生,不在此列
// =====================================================

export const AuditEventType = {
  // ===== 用户事件(AUTH) =====
  LOGIN_SUCCESS: 'AUTH:LOGIN_SUCCESS',
  LOGIN_FAILED: 'AUTH:LOGIN_FAILED',
  LOGOUT: 'AUTH:LOGOUT',
  PASSWORD_CHANGED: 'AUTH:PASSWORD_CHANGED',
  MFA_ENABLED: 'AUTH:MFA_ENABLED',
  MFA_DISABLED: 'AUTH:MFA_DISABLED',
  MFA_CHALLENGE_SUCCESS: 'AUTH:MFA_CHALLENGE_SUCCESS',
  MFA_CHALLENGE_FAILED: 'AUTH:MFA_CHALLENGE_FAILED',
  ACCOUNT_LOCKED: 'AUTH:ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'AUTH:ACCOUNT_UNLOCKED',

  // ===== 安全事件(SECURITY) =====
  ACCESS_DENIED: 'SECURITY:ACCESS_DENIED',       // RBAC 403
  BRUTE_FORCE_ATTEMPT: 'SECURITY:BRUTE_FORCE_ATTEMPT', // 登录爆破
  AUDIT_TAMPER_ATTEMPT: 'SECURITY:AUDIT_TAMPER_ATTEMPT', // 审计篡改尝试
  SENSITIVE_ACCESS: 'SECURITY:SENSITIVE_ACCESS', // 敏感数据访问(审计日志导出等)
  MFA_REQUIRED_FAILED: 'SECURITY:MFA_REQUIRED_FAILED', // MFA 二次验证缺失

  // ===== 系统事件(SYSTEM) =====
  SYSTEM_START: 'SYSTEM:START',
  SYSTEM_SHUTDOWN: 'SYSTEM:SHUTDOWN',
  SYSTEM_ERROR: 'SYSTEM:ERROR',
  BACKUP_COMPLETED: 'SYSTEM:BACKUP_COMPLETED',
  BACKUP_FAILED: 'SYSTEM:BACKUP_FAILED',
  BACKUP_RESTORE: 'SYSTEM:BACKUP_RESTORE',

  // ===== 配置事件(CONFIG) =====
  PERMISSION_CHANGED: 'CONFIG:PERMISSION_CHANGED', // 角色/权限变更
  SETTINGS_CHANGED: 'CONFIG:SETTINGS_CHANGED',     // 系统参数变更

  // ===== 业务事件 — 设备(EQUIPMENT) =====
  // CNAS §6.5 设备 + §7.7 期间核查
  EQUIPMENT_REGISTERED: 'EQUIPMENT:REGISTERED',
  EQUIPMENT_RETIRED: 'EQUIPMENT:RETIRED',
  CALIBRATION_PASSED: 'EQUIPMENT:CALIBRATION_PASSED',
  CALIBRATION_FAILED: 'EQUIPMENT:CALIBRATION_FAILED',
  CALIBRATION_OVERDUE: 'EQUIPMENT:CALIBRATION_OVERDUE',
  PERIODIC_CHECK_PASSED: 'EQUIPMENT:PERIODIC_CHECK_PASSED',
  PERIODIC_CHECK_FAILED: 'EQUIPMENT:PERIODIC_CHECK_FAILED',

  // ===== 业务事件 — 样品(SAMPLE) =====
  SAMPLE_RECEIVED: 'SAMPLE:RECEIVED',
  SAMPLE_DISPOSED: 'SAMPLE:DISPOSED',
  SAMPLE_RETENTION_TRANSFER: 'SAMPLE:RETENTION_TRANSFER',
  SAMPLE_STATUS_TRANSITIONED: 'SAMPLE:STATUS_TRANSITIONED',
  SAMPLE_ARCHIVED: 'SAMPLE:ARCHIVED',

  // ===== 业务事件 — QC =====
  // CNAS §7.7 期间核查
  QC_MEASUREMENT_RECORDED: 'QC:MEASUREMENT_RECORDED',
  WESTGARD_VIOLATION_1_3S: 'QC:WESTGARD_1_3S',
  WESTGARD_VIOLATION_2_2S: 'QC:WESTGARD_2_2S',
  WESTGARD_VIOLATION_R_4S: 'QC:WESTGARD_R_4S',
  WESTGARD_VIOLATION_4_1S: 'QC:WESTGARD_4_1S',
  WESTGARD_VIOLATION_10X: 'QC:WESTGARD_10X',

  // ===== 业务事件 — 不符合工作 =====
  // CNAS §7.9 OOS + §7.10 不符合
  OOS_OPENED: 'OOS:OPENED',
  OOS_INVESTIGATING: 'OOS:INVESTIGATING',
  OOS_CLOSED: 'OOS:CLOSED',
  CAPA_OPENED: 'CAPA:OPENED',
  CAPA_APPROVED: 'CAPA:APPROVED',
  CAPA_CLOSED: 'CAPA:CLOSED',

  // ===== 业务事件 — 报告 =====
  // CNAS §7.8 结果报告
  REPORT_DRAFTED: 'REPORT:DRAFTED',
  REPORT_REVIEWED: 'REPORT:REVIEWED',
  REPORT_APPROVED: 'REPORT:APPROVED',
  REPORT_ISSUED: 'REPORT:ISSUED',
  REPORT_AMENDED: 'REPORT:AMENDED',
  REPORT_WITHDRAWN: 'REPORT:WITHDRAWN',
  REPORT_SIGNED: 'REPORT:SIGNED',      // 21 CFR Part 11 电子签名
  REPORT_PDF_GENERATED: 'REPORT:PDF_GENERATED',

  // W1 架构:SoD 互斥违规(CNAS-CL01:2018 §7.8.4 + ISO 17025:2017 §7.5.3)
  SOD_VIOLATION_BLOCKED: 'SOD:VIOLATION_BLOCKED',

  // ===== 业务事件 — 标准物质 =====
  // CNAS §7.6 测量溯源性
  REFERENCE_MATERIAL_REGISTERED: 'RM:REGISTERED',
  REFERENCE_MATERIAL_USED: 'RM:USED',
  REFERENCE_MATERIAL_EXPIRED: 'RM:EXPIRED',
  REFERENCE_MATERIAL_BLOCKED: 'RM:BLOCKED',   // 过期阻断使用

  // ===== 业务事件 — 环境 =====
  // CNAS §7.5 设施与环境条件
  ENVIRONMENT_OUT_OF_RANGE: 'ENVIRONMENT:OUT_OF_RANGE',
  ENVIRONMENT_RESTORED: 'ENVIRONMENT:RESTORED',

  // ===== 业务事件 — 人员 =====
  // CNAS §7.2 人员
  PERSONNEL_AUTHORIZED: 'PERSONNEL:AUTHORIZED',
  PERSONNEL_SUSPENDED: 'PERSONNEL:SUSPENDED',
  TRAINING_COMPLETED: 'PERSONNEL:TRAINING_COMPLETED',
  COMPETENCY_ASSESSED: 'PERSONNEL:COMPETENCY_ASSESSED',

  // ===== 业务事件 — 内审 / 管评 =====
  // CNAS §8.8 内审 + §8.9 管评
  INTERNAL_AUDIT_OPENED: 'AUDIT:INTERNAL_OPENED',
  INTERNAL_AUDIT_CLOSED: 'AUDIT:INTERNAL_CLOSED',
  MANAGEMENT_REVIEW_OPENED: 'AUDIT:MANAGEMENT_OPENED',
  MANAGEMENT_REVIEW_CLOSED: 'AUDIT:MANAGEMENT_CLOSED',
  SUPERVISION_RECORDED: 'AUDIT:SUPERVISION_RECORDED',
  NCR_CAPA_LINKED: 'NCR:CAPA_LINKED',

  // ===== 业务事件 — 仪器对接 =====
  // P1-5 检测仪器 mTLS 上报
  INSTRUMENT_DATA_RECEIVED: 'INSTRUMENT:DATA_RECEIVED',
  INSTRUMENT_DATA_REJECTED: 'INSTRUMENT:DATA_REJECTED',

  // ===== 业务事件 — 反向操作(撤销/删除/作废,ALCOA+ 留痕) =====
  RECORD_DELETED: 'DATA:RECORD_DELETED',          // 软删除
  RECORD_VOIDED: 'DATA:RECORD_VOIDED',            // 作废(标记 VOID)
  RECORD_ROLLED_BACK: 'DATA:RECORD_ROLLED_BACK',  // 状态回退
  RECORD_UNDONE: 'DATA:RECORD_UNDONE',            // 撤销(领用撤销等)
} as const;

export type AuditEventTypeValue = (typeof AuditEventType)[keyof typeof AuditEventType];
